% -------------------------------------------------------------------
%  Generated by MATLAB on 31-Mar-2026 12:48:41
%  MATLAB version: 24.1.0.2537033 (R2024a)
% -------------------------------------------------------------------
saveVarsMat = load('thermo_clear.mat');

A = 0.0123;

A1 = 0.0123;

A2 = 0.0411;

Cd = 0.1;

Cd1 = 0.1;

Cd2 = 0.4;

Ki = 0.05;

Kp = 0.2;

Ts = 0.15;

g = 9.81;

m = 1;

out = saveVarsMat.out; % <1x1 Simulink.SimulationOutput> unsupported class

rho = 1.225;

clear saveVarsMat;
